# SPDX-FileCopyrightText: 2021 The CC: Tweaked Developers
# SPDX-FileCopyrightText: 2026 Vynzaro
#
# SPDX-License-Identifier: MPL-2.0

modLoader="javafml"
loaderVersion="[30,)"

issueTrackerURL="https://github.com/Vynzaro/CC-Rewired/issues"
displayURL="https://github.com/Vynzaro/CC-Rewired"

credits="Created by Daniel Ratcliffe (@DanTwoHundred)"
authors="Vynzaro and CC: Rewired contributors"
license="ComputerCraft Public License 1.0 and other file-level licenses"

[[mods]]
modId="cctest"
version="1.0.0"
displayName="CC: Rewired test framework"
description='''
A test framework for ensuring CC: Rewired works correctly.
'''

[[dependencies.cctest]]
modId="computercraft"
mandatory=true
versionRange="[1.0,)"
ordering="AFTER"
side="BOTH"
