# SPDX-FileCopyrightText: 2017 The CC: Tweaked Developers
# SPDX-FileCopyrightText: 2026 Vynzaro
#
# SPDX-License-Identifier: MPL-2.0

org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.configuration-cache=true

kotlin.stdlib.default.dependency=false
kotlin.jvm.target.validation.mode=error

# Mod properties
modVersion=0.1.0-alpha.1

isUnstable=true
